### ISSUE TITLE
Can't test it at the moment, general questions

### ISSUE THREAD

**Issue by Hokage3211** [jetdog8808/Platform-Link#1]
Firstly just wanted to say it looks cool, and looks like it works well!
I saw in the video on the vrchat discord that the feet aren't moving on the platform, are you teleporting or using a station to move them? How does the syncing work across clients? If it's using a station to move them, how does it handle turning? (otherwise if it's teleport that's an easy question: you don't have to handle turning)

**Comment by jetdog8808** [comment]
Thanks for the compliments.
- The feet were not moving cause I was in fullbody with locomotion off. Recorded a quick example in desktop

https://github.com/jetdog8808/Platform-Link/assets/36026251/2504047b-b9a2-49c6-95cc-d77b715a191f

- I'm teleporting to move the player.
- Syncing is done with vrchats builtin ik sync. So there will be about a half second delay between clients.
